# This file was generated by GoReleaser. DO NOT EDIT.
cask "strava-mcp" do
  version "1.0"

  on_macos do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_amd64.tar.gz"
      sha256 "40d3f5800bfff0c54466e56e55a500e5027a232631b15200aeaf8773289169e3"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_arm64.tar.gz"
      sha256 "79ef7f3ce41801738424e29e0e245b2193da8f2fb9877647c99f562fab6fe412"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_amd64.tar.gz"
      sha256 "f06fe4317abd05dbf92f801b019324c82e4a2903d747012d7ed0dcb0c7b2009a"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_arm64.tar.gz"
      sha256 "31452e4a51ad4a5de9506f031ba6e210428c7090570ff91ed53689982b57aa3c"
    end
  end

  name "strava-mcp"
  desc "MCP server for Strava API - local Go binary with zero cloud infrastructure"
  homepage "https://github.com/Stealinglight/StravaMCP"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strava-mcp"

  # No zap stanza required

end
