# This file was generated by GoReleaser. DO NOT EDIT.
cask "strava-mcp" do
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_amd64.tar.gz"
      sha256 "73e46fdc97be470964bd9240c0eeb926a57433f05c024c3b1bc5bb636b192d8d"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_arm64.tar.gz"
      sha256 "c3eed7ed8062346432756efabcc1352b3777f6d71eee63c30dedb8a5f7fb9aeb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_amd64.tar.gz"
      sha256 "5e1ca35e25d16839053f4e5157d1edb953d66406ce9f84e5f2cbb2d89ddf994a"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_arm64.tar.gz"
      sha256 "f9b75577993ab757d4948cb6ec27ada5903d8ef81cbc9786414436d48c1c876d"
    end
  end

  name "strava-mcp"
  desc "MCP server for Strava API - local Go binary with zero cloud infrastructure"
  homepage "https://github.com/Stealinglight/StravaMCP"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strava-mcp"

  # No zap stanza required

end
