# This file was generated by GoReleaser. DO NOT EDIT.
cask "strava-mcp" do
  version "1.1.1"

  on_macos do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_amd64.tar.gz"
      sha256 "4e23a753caa3b71a120152e875fc8d656080a3dd270189851b32205a88c0b856"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_darwin_arm64.tar.gz"
      sha256 "3ff4d565c33263d817ee5ffdd3c5a2998ae510dce96c71e9ba1bb2c3025fa1cd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_amd64.tar.gz"
      sha256 "d0be616861376e8f4c4cf45dd22d0200149e83cd258249d652072b27bf004072"
    end
    on_arm do
      url "https://github.com/Stealinglight/StravaMCP/releases/download/v#{version}/StravaMCP_#{version}_linux_arm64.tar.gz"
      sha256 "9e40a3eba92b6a0cf4cc11e0da1fd2469909af8afaf04b50812d2c01387d4f8b"
    end
  end

  name "strava-mcp"
  desc "MCP server for Strava API - local Go binary with zero cloud infrastructure"
  homepage "https://github.com/Stealinglight/StravaMCP"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strava-mcp"

  # No zap stanza required

end
